server:
  port: 8001
  servlet:
    context-path: /
    
spring:     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itsminedb2?serverTimezone=Asia/Seoul
    username: dong1
    password: gml7439416
  servlet:    multipart:      max-file-size: 10MB      max-request-size: 20MB    
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
    
